Package vs Struct / Interface Decision
REAK-INFOTECH-LLP/reakgo pull request #16
Opened 2023-09-19 14:27 UTC by eclipsed-ninja

We need to identify if packages would be better for our use-case or we need to switch to struct / interface for promoted methods.

More details will be added later.

2023-09-19 14:29 UTC, eclipsed-ninja commented
I've tested and also have taken a look at other frameworks on how they implement this, I agree and understood that removing the current controller.go logic is definitely much needed as it's useless housekeeping to manage all the model functions at a single place.

The outcome so far is we cannot remove packages at all, Packages unfortunately would be here to stay because there is no way we can divide the same package into different folders. If we're using different folders then its not possible to use the same package, and organizing code becomes very difficult.

I'm currently looking at ways on how we can make it happen without controllers.go

2023-09-20 08:05 UTC, eclipsed-ninja commented
The setup is changed as you can review in the PR. we no longer need model registration in controller.go

Take a look and let me know if there are any issues, We might need to add a new issue as what code we'll place in controllers.go and models.go, the code would be similar to utility but limited to the respective packages.

2023-09-21 11:52 UTC, RajP7Jowa requested changes

2023-09-21 11:52 UTC, RajP7Jowa commented on models/models.go
> +var (
can we are remove to this variable re-declare  on every page (module)
i means i want re-usability on every where

2023-09-21 11:57 UTC, RajP7Jowa approved these changes

2023-09-22 06:33 UTC, GuitarGeekCoder approved these changes

2023-09-22 11:30 UTC, merged